/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pl.allegro.devskiller

import pl.allegro.devskiller.domain.assignments.AssignmentsStatistics
import pl.allegro.devskiller.infrastructure.SlackAssignmentsNotifier

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val slackApp = com.slack.api.bolt.App()
    val notifier = SlackAssignmentsNotifier(slackApp.client)
    notifier.notifyAboutCurrentAssignments(AssignmentsStatistics("xdd"))
}
